DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS transactions;

CREATE TABLE accounts
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner   VARCHAR(100) NOT NULL UNIQUE,
    balance NUMERIC      NOT NULL
);

CREATE TABLE transactions
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT REFERENCES accounts (id) ON DELETE CASCADE,
    type       VARCHAR(30) NOT NULL,
    amount     NUMERIC     NOT NULL,
    time       TIMESTAMP
);